### ISSUE TITLE
Add CI/PHPUnit tests

### ISSUE THREAD

**Issue by kefzce** [dns2316/php-experience#2]
use:
[travis-ci.org](travis-ci.org/kefzce/bot-class)
[https://scrutinizer-ci.com](https://scrutinizer-ci.com/)

**Comment by kefzce** [comment]
я напишу тесты, за тобой CI и статический анализ

**Comment by dns2316** [comment]
Подключил travis-ci & scrutinizer-ci

**Comment by kefzce** [comment]
#4
